// Generated by `wit-bindgen` 0.36.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_register_routes_cabi<T: Guest>() {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    T::register_routes();
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_sql_create_cabi<T: Guest>(arg0: *mut u8, arg1: usize) {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    T::sql_create(_rt::string_lift(bytes0));
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_sql_delete_cabi<T: Guest>(arg0: *mut u8, arg1: usize) {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    T::sql_delete(_rt::string_lift(bytes0));
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_sql_list_cabi<T: Guest>(arg0: *mut u8, arg1: usize) {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    T::sql_list(_rt::string_lift(bytes0));
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_sql_query_cabi<T: Guest>(arg0: *mut u8, arg1: usize) {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    T::sql_query(_rt::string_lift(bytes0));
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_sql_execute_cabi<T: Guest>(arg0: *mut u8, arg1: usize) {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    T::sql_execute(_rt::string_lift(bytes0));
}
pub trait Guest {
    fn register_routes();
    fn sql_create(cmd: _rt::String);
    fn sql_delete(cmd: _rt::String);
    fn sql_list(cmd: _rt::String);
    fn sql_query(cmd: _rt::String);
    fn sql_execute(cmd: _rt::String);
}
#[doc(hidden)]
macro_rules! __export_world_klave_rust_postgre_template_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[export_name = "register-routes"] unsafe extern "C" fn
        export_register_routes() { $($path_to_types)*::
        _export_register_routes_cabi::<$ty > () } #[export_name = "sql-create"] unsafe
        extern "C" fn export_sql_create(arg0 : * mut u8, arg1 : usize,) {
        $($path_to_types)*:: _export_sql_create_cabi::<$ty > (arg0, arg1) } #[export_name
        = "sql-delete"] unsafe extern "C" fn export_sql_delete(arg0 : * mut u8, arg1 :
        usize,) { $($path_to_types)*:: _export_sql_delete_cabi::<$ty > (arg0, arg1) }
        #[export_name = "sql-list"] unsafe extern "C" fn export_sql_list(arg0 : * mut u8,
        arg1 : usize,) { $($path_to_types)*:: _export_sql_list_cabi::<$ty > (arg0, arg1)
        } #[export_name = "sql-query"] unsafe extern "C" fn export_sql_query(arg0 : * mut
        u8, arg1 : usize,) { $($path_to_types)*:: _export_sql_query_cabi::<$ty > (arg0,
        arg1) } #[export_name = "sql-execute"] unsafe extern "C" fn
        export_sql_execute(arg0 : * mut u8, arg1 : usize,) { $($path_to_types)*::
        _export_sql_execute_cabi::<$ty > (arg0, arg1) } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_klave_rust_postgre_template_cabi;
#[rustfmt::skip]
mod _rt {
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub use alloc_crate::string::String;
    extern crate alloc as alloc_crate;
}
/// Generates `#[no_mangle]` functions to export the specified type as the
/// root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_klave_rust_postgre_template_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_klave_rust_postgre_template_cabi!($ty
        with_types_in $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_klave_rust_postgre_template_impl as export;
#[cfg(target_arch = "wasm32")]
#[link_section = "component-type:wit-bindgen:0.36.0:component:klave-ai-rag:klave-rust-postgre-template:encoded world"]
#[doc(hidden)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 315] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xa9\x01\x01A\x02\x01\
A\x08\x01@\0\x01\0\x04\0\x0fregister-routes\x01\0\x01@\x01\x03cmds\x01\0\x04\0\x0a\
sql-create\x01\x01\x04\0\x0asql-delete\x01\x01\x04\0\x08sql-list\x01\x01\x04\0\x09\
sql-query\x01\x01\x04\0\x0bsql-execute\x01\x01\x04\02component:klave-ai-rag/klav\
e-rust-postgre-template\x04\0\x0b!\x01\0\x1bklave-rust-postgre-template\x03\0\0\0\
G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.220.1\x10wit-bindge\
n-rust\x060.36.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
